#language: node_js
#node_js: "8"
#os:
#  - linux
#  - osx

os: linux
language: android
android:
  components:
    - android-28

#matrix:
#  include:
#    - os: osx
#      language: node_js
#      node_js: "8"
#    - os: linux
#      android:
#      components:
#        - android-28

before_install:
  -  |
  # Using Ubuntu
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - &&
  sudo apt-get install -y nodejs
install:
  - npm install

script: 
  - npm run cordova-build-android
#script:
#  - npm run electron:publish

cache:
  directories:
    - node_modules