os: linux
language: node_js
node_js: "8"

install:
  - npm install

script: 
  - npm run build

deploy:
  - provider: surge
    project: ./dist/
    domain: https://condc-dev.surge.sh
    on: development
    skip_cleanup: true
  - provider: surge
    project: ./dist/
    domain: https://condc-app.surge.sh
    on: master
    skip_cleanup: true


cache:
  directories:
    - node_modules