#language: node_js
#node_js: "8"
#os:
#  - linux
#  - osx

#os:
#  - linux
#  - osx

#language:
#  - android

matrix:
  include:
    - name: "iOS App Build"
      os: osx
      env: MODE=OSX
    - name: "Android App Build"
      os: linux
      language: android
      env: MODE=LINUX
      android:
        components:
          - android-28
    - name: "General Unit Tests"
      os: linux
      language: node_js
      node_js: "8"
      env: MODE=TEST

before_install:
  - |
    if [ "$MODE" == "TEST" ]; then
      echo "not installing node"
    else
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y nodejs
    fi

    
install:
  - npm install

script: 
  - |
    if [ "$MODE" == "LINUX"]; then
      npm run cordova-build-android
    else
      if [ "$MODE" == "OSX"]; then
        npm run cordova-build-ios
      else
        npm run test:unit
      fi
    fi
#script:
#  - npm run electron:publish

cache:
  directories:
    - node_modules